"""empty message

Revision ID: 3a3e6bb0e157
Revises: 
Create Date: 2023-07-17 01:23:01.339595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3e6bb0e157'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ttlCost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('expense', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('illustrations',
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('illustitle', sa.String(length=80), nullable=True),
    sa.Column('piece', sa.String(length=80), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('universe', sa.String(length=80), nullable=True),
    sa.Column('illcription', sa.String(length=1024), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=False),
    sa.Column('dateCompleted', sa.DateTime(), nullable=False),
    sa.Column('medium', sa.String(length=80), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('iid')
    )
    op.create_table('income_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('monthlyEarning', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_channel')
    op.drop_table('illustrations')
    op.drop_table('expense_list')
    op.drop_table('expense_categories')
    op.drop_table('account')
    # ### end Alembic commands ###
