"""empty message

Revision ID: 90c8dd93d179
Revises: 5ff9e22a2f23
Create Date: 2023-07-17 16:22:57.415387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c8dd93d179'
down_revision = '5ff9e22a2f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_channel', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
