"""empty message

Revision ID: b8b4f635084b
Revises: 92aca0edf5eb
Create Date: 2023-07-18 00:54:06.160082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b4f635084b'
down_revision = '92aca0edf5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_type', sa.String(length=255), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('income_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_channel', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    with op.batch_alter_table('expense_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('expense_type')

    # ### end Alembic commands ###
