"""empty message

Revision ID: de25414bbc1d
Revises: 359d7a40713d
Create Date: 2023-07-21 13:43:28.831673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de25414bbc1d'
down_revision = '359d7a40713d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_list', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_list', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
